app_report/urls.py
from django.urls import path
from app_report.views import *


app_name = 'app_report'
urlpatterns = [
    path('report/', report_with_flexmonster, name = 'report_with_flexmonster'),
    path('pivot-data/', pivot_data, name='pivot_data'),
]

urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from app_store.views import ProductViewSet

router = routers.DefaultRouter()
router.register('san-pham', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_store.urls')),
    path('', include('app_customer.urls')),
    path('', include('app_cart.urls')),
    path('', include('app_admin.urls')),
    path('', include('app_report.urls')),
    path('', include('app_analysis.urls')),
    path('', include('app_visualization.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_report/models.py
from django.db import models

# Create your models here.

app_report/views.py
from django.shortcuts import render
from django.http import JsonResponse
from app_store.models import Product
from django.core import serializers


# Create your views here.
def report_with_flexmonster(request):
    return render(request, 'report_with_flexmonster.html', {

    })

def pivot_data(request):
    dataset = Product.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)

app_report/templates/report_with_flexmonster.html
<html>

<head>
    <meta charset="UTF-8">
    <title>Dashboard with Flexmonster</title>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css" />
</head>

<body>
    <div id="pivot-table-container" data-url="{% url 'app_report:pivot_data' %}"></div>
    <div id="pivot-chart-container"></div>
    <script>
        function processData(dataset) {
            var result = []
            dataset = JSON.parse(dataset);
            dataset.forEach(item => result.push(item.fields));
            return result;
        }
        $.ajax({
            url: $("#pivot-table-container").attr("data-url"),
            dataType: 'json',
            success: function (data) {
                new Flexmonster({
                    container: "#pivot-table-container",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processData(data)
                        },
                        slice: {}
                    }
                });
                new Flexmonster({
                    container: "#pivot-chart-container",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    //toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processData(data)
                        },
                        slice: {},
                        "options": {
                            "viewType": "charts",
                            "chart": {
                                "type": "pie"
                            }
                        }
                    }
                });
            }
        });

    </script>
</body>

</html>