app_cart/urls.py
from django.urls import path
from app_cart.views import *


app_name = 'app_cart'
urlpatterns = [
    path('gio-hang/', gio_hang, name='gio_hang'),
    path('mua-ngay/<int:product_id>/', mua_ngay, name='mua_ngay'),
    path('xoa-san-pham/<int:product_id>/', xoa_san_pham, name='xoa_san_pham'),
    path('thanh-toan/', thanh_toan, name='thanh_toan'),
    path('them-vao-gio-hang/<int:product_id>/', them_vao_gio_hang, name='them_vao_gio_hang'),
]

app_customer/urls.py
from django.urls import path
from app_customer.views import *


app_name = 'app_customer'
urlpatterns = [
    path('dang-nhap/', dang_nhap_dang_ky, name='dang_nhap_dang_ky'),
    path('dang-xuat/', dang_xuat, name='dang_xuat'),
    path('thong-tin-cua-toi/', thong_tin_cua_toi, name='thong_tin_cua_toi'),
    path('xuat-bao-cao-don-hang/<int:order_id>/', xuat_bao_cao_don_hang, name='xuat_bao_cao_don_hang'),
]

app_store/urls.py
from django.urls import path
from app_store.views import *


app_name = 'app_store'
urlpatterns = [
    path('', trang_chu, name='trang_chu'),
    path('trang-chu-2/', trang_chu_2, name='trang_chu_2'),
    path('danh-muc/<int:id_subcategory>/', danh_muc, name='danh_muc'),  # danh-muc/0/
    path('san-pham/<int:id_product>/', san_pham, name='san_pham'),      # san-pham/123/
    path('lien-he/', lien_he, name='lien_he'),
    path('rss/', rss, name='rss'),
    path('products-service/', products_service, name='products_service'),
    path('tim-kiem/', tim_kiem, name='tim_kiem'),
]

urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from app_store.views import ProductViewSet

router = routers.DefaultRouter()
router.register('san-pham', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_store.urls')),
    path('', include('app_customer.urls')),
    path('', include('app_cart.urls')),
    path('', include('app_admin.urls')),
    path('', include('app_report.urls')),
    path('', include('app_analysis.urls')),
    path('', include('app_visualization.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_store/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=150, unique=True)
    image = models.ImageField(upload_to='store/images', default='store/images/default.png')

    def __str__(self):
        return self.name


class Product(models.Model):
    subcategory = models.ForeignKey(SubCategory, on_delete=models.PROTECT, related_name='products')
    name = models.CharField(max_length=250)
    price = models.FloatField(default=0.0)
    price_origin = models.FloatField(null=True)
    image = models.ImageField(upload_to='store/images', default='store/images/default.png')
    content = models.TextField(blank=True, null=True)
    public_day = models.DateTimeField(default=timezone.now)
    viewed = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20, null=True)
    subject = models.CharField(max_length=264)
    message = models.TextField()
    created_day = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.subject


class Slider(models.Model):
    caption = models.CharField(max_length=250, unique=True)
    link = models.URLField(null=True)
    image = models.ImageField(upload_to='store/sliders', default='store/sliders/default.png')

    def __str__(self):
        return self.caption


class Brand(models.Model):
    name = models.CharField(max_length=150, unique=True)
    image = models.ImageField(upload_to='store/brands', default='store/brands/default.png')

    def __str__(self):
        return self.name

app_store/views.py
from django.shortcuts import render, redirect, reverse
from django. core.mail import send_mail, EmailMultiAlternatives
from rest_framework import viewsets, permissions
from django.http import JsonResponse
from django.conf import settings
from app_store.models import Slider, Brand, SubCategory, Product, Contact
from app_store.serializer import ProductSerializer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from app_cart.cart import Cart
from app_cart.views import them_vao_gio_hang
import feedparser
from urllib.parse import urlencode



# Create your views here.
def trang_chu(request):
    # Slider
    sliders = Slider.objects.all()

    # Brand
    brands = Brand.objects.all()

    # Thiết bị gia đình
    subcategories_tbgd = SubCategory.objects.filter(category=1).values('id')
    list_id_subcategories_tbgd = [item['id'] for item in list(subcategories_tbgd)]
    products_tbgd = Product.objects.filter(subcategory__in=list_id_subcategories_tbgd).order_by('-public_day')[:20]

    # Đồ dùng nhà bếp
    subcategories_ddnb = SubCategory.objects.filter(category=2).values('id')
    list_id_subcategories_ddnb = [item['id'] for item in list(subcategories_ddnb)]
    products_ddnb = Product.objects.filter(subcategory__in=list_id_subcategories_ddnb).order_by('-public_day')[:20]

    #giỏ hàng
    cart = Cart(request)

    return render(request, 'index.html', {
        'sliders': sliders,
        'brands': brands,
        'products_tbgd': products_tbgd,
        'products_ddnb': products_ddnb,
        'cart': cart,
    })


def trang_chu_2(request):
    # Slider
    sliders = Slider.objects.all()

    # Brand
    brands = Brand.objects.all()

    # Thiết bị gia đình
    subcategories_tbgd = SubCategory.objects.filter(category=1).values('id')
    list_id_subcategories_tbgd = [item['id'] for item in list(subcategories_tbgd)]
    products_tbgd = Product.objects.filter(subcategory__in=list_id_subcategories_tbgd).order_by('-public_day')[:20]

    # Đồ dùng nhà bếp
    subcategories_ddnb = SubCategory.objects.filter(category=2).values('id')
    list_id_subcategories_ddnb = [item['id'] for item in list(subcategories_ddnb)]
    products_ddnb = Product.objects.filter(subcategory__in=list_id_subcategories_ddnb).order_by('-public_day')[:20]

    # Tính số lần truy cập
    so_lan = 0
    if request.COOKIES.get('so_lan_truy_cap'):
        so_lan = int(request.COOKIES.get('so_lan_truy_cap'))

    response = render(request, 'index-2.html', {
        'sliders': sliders,
        'brands': brands,
        'products_tbgd': products_tbgd,
        'products_ddnb': products_ddnb,
    })

    response.set_cookie('so_lan_truy_cap', so_lan + 1, 5)

    return response


def danh_muc(request, id_subcategory):

    #giỏ hàng
    cart = Cart(request)

    # Đọc danh sách subcategory
    subcategories = SubCategory.objects.order_by('name')

    # Brand
    brands = Brand.objects.all()


    # Lọc sản phẩm theo danh mục
    if id_subcategory == 0:
        products = Product.objects.order_by('-public_day')
        subcategory_name = f'Tất cả sản phẩm ({products.count()})'
    else:
        products = Product.objects.filter(subcategory=id_subcategory).order_by('-public_day')
        subcategory = SubCategory.objects.get(pk=id_subcategory)
        subcategory_name = f'{subcategory.name} ({products.count()})'
    
    #lọc theo giá
    keyword = ''
    price = ''
    if request.GET.get('gia'):
        price = request.GET.get('gia') #
        from_price, to_price = price.split('-')
        '''
         __lte -> Less than or equal
         __gte -> Greater than or equal
         __lt -> Less than
         __gt -> Greater than
        '''
        if id_subcategory == 0:
            keyword = request.GET.get('tu_khoa').strip()
            products = Product.objects.filter(price__gte=from_price).order_by('-public_day')
            if to_price != '':
                products = Product.objects.filter(price__gte=from_price,
                                                  price__lt=to_price).order_by('-public_day')
                if keyword != '':
                    products = Product.objects.filter(price__gte=from_price,
                                                      price__lt=to_price,
                                                      name__contains=keyword).order_by('-public_day')
            subcategory_name = f'Tất cả sản phẩm ({products.count()})' 
        else:
            
            products = Product.objects.filter(subcategory=id_subcategory,
                                              price__gte=from_price).order_by('-public_day')
            if to_price != '':
                products = Product.objects.filter(subcategory=id_subcategory,
                                                  price__gte=from_price,
                                                  price__lt=to_price).order_by('-public_day')
                if keyword != '':
                    products = Product.objects.filter(subcategory=id_subcategory,
                                                  price__gte=from_price,
                                                  price__lt=to_price,
                                                  name__contains=keyword).order_by('-public_day')
            subcategory = SubCategory.objects.get(pk=id_subcategory)
            subcategory_name = f'{subcategory.name} ({products.count()})' 

    # Phân trang
    stories_per_page = 9
    page = request.GET.get('trang', 1)
    paginator = Paginator(products, stories_per_page)
    try:
        products_pager = paginator.page(page)
    except PageNotAnInteger:
        products_pager = paginator.page(1)
    except EmptyPage:
        products_pager = paginator.page(paginator.num_pages)

    return render(request, 'product-list.html', {
        'subcategories': subcategories,
        'products_pager': products_pager,
        'products': products,
        'subcategory_name': subcategory_name,
        'brands': brands,
        'cart': cart,
        'keyword': keyword,
    })


def san_pham(request, id_product):

    #giỏ hàng
    cart = Cart(request)

    # Đọc danh sách subcategory
    subcategories = SubCategory.objects.order_by('name')

    # Brand
    brands = Brand.objects.all()

    # Chi tiết sản phẩm
    product = Product.objects.get(pk=id_product)

    # Sản phẩm liên quan
    subcategory = product.subcategory
    related_products = Product.objects.filter(subcategory=subcategory.pk).exclude(pk=id_product).order_by('-public_day')[:20]
    
    #tên danh mục
    subcategory_name = subcategory.name

    # lấy id danh mục
    subcategory_id = subcategory.pk

    #them_vao_gio_hang
    quantity = 1
    if request.POST.get('btnThemVaoGioHang'):
        quantity = int(request.POST.get('quantity'))
        them_vao_gio_hang(request, id_product, quantity)
        cart = Cart(request)


    return render(request, 'product-detail.html', {
        'subcategories': subcategories,
        'brands': brands,
        'product': product,
        'related_products': related_products,
        'cart': cart,
        'subcategory_name': subcategory_name,
        'subcategory_id': subcategory_id,
        'cart':cart,
        'quantity': quantity,
    })


def lien_he(request):

    #giỏ hàng
    cart = Cart(request)
    chuoi_ket_qua = ''
    if request.POST.get("ho_ten"):
        #gán biến
        ho_ten=request.POST.get('ho_ten')
        dien_thoai=request.POST.get('dien_thoai')
        email=request.POST.get('email')
        tieu_de=request.POST.get('tieu_de')
        tin_nhan=request.POST.get('tin_nhan')

        lien_he = Contact(name=ho_ten,
                          phone_number=dien_thoai,
                          email=email,
                          subject=tieu_de,
                          message=tin_nhan)
        lien_he.save()

         # gửi mail khi không có định dạng HTML
        #noi_dung = 'Chúng tôi nhận được tin nhắn của bạn với nội dung như sau: \n ' 
        #noi_dung += f'{tin_nhan} \n'
        #noi_dung += ' Chúng tôi sẽ phản hồi trong thời gian sớm nhất. Xin chân thành cảm ơn!'
        sender = settings.EMAIL_HOST_USER
        danh_sach_nguoi_nhan  = [email, sender]
        #send_mail(tieu_de, noi_dung, sender,danh_sach_nguoi_nhan)


         # gửi mail khi không có định dạng HTML
        noi_dung = '<p>Chúng tôi nhận được tin nhắn của bạn với nội dung như sau: </p>  ' 
        noi_dung += f'<p><b>{tin_nhan} </b></p>'
        noi_dung += '<p>Chúng tôi sẽ phản hồi trong thời gian sớm nhất. Xin chân thành cảm ơn!  </p>'
        msg = EmailMultiAlternatives(tieu_de, noi_dung, sender,danh_sach_nguoi_nhan)
        msg.attach_alternative(noi_dung,'text/html')
        msg.send()


        chuoi_ket_qua = '''
        <div class="alert alert-success" role="alert">
            Gửi thông tin thành công!
        </div>
        '''
        
        


    return render(request, 'contact.html', {
        'cart': cart,
        'chuoi_ket_qua': chuoi_ket_qua,
    })




def tim_kiem(request):
     #giỏ hàng
    cart = Cart(request)

    # Đọc danh sách subcategory
    subcategories = SubCategory.objects.order_by('name')

    # Brand
    brands = Brand.objects.all()

    #tìm kiếm
    subcategory_name =''
    keyword = ''
    if request.GET.get('tu_khoa'):
        keyword = request.GET.get('tu_khoa').strip()
        products = Product.objects.filter(name__contains=keyword).order_by('-public_day')
        subcategory_name = f'Tìm thấy {products.count()} sản phẩm'

    if request.GET.get('gia'):
        price = request.GET.get('gia')
        keyword = request.GET.get('tu_khoa')
        base_url = reverse('app_store:danh_muc', kwargs={'id_subcategory':0})
        query_tring = urlencode({
            'gia': price,
            'tu_khoa': keyword,
        })
        url = f'{base_url}?{query_tring}'
        return redirect(url)

    # Phân trang:
    
    stories_per_page = 9
    page = request.GET.get('trang', 1)
    paginator = Paginator(products, stories_per_page)
    try:

app_store/templates/_Master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EStore | {% block title_tab %}{% endblock %}</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            jQuery(function ($) {
                let path = window.location.href; 
                $('.mn a').each(function () {
                    if (this.href === path){
                        $(this).addClass('active')
                    }
                });
            });
        </script>
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        chinguyen.hcmus@gmail.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        +012-345-6789
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->
        
        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto mn">
                            <a href="{% url 'app_store:trang_chu' %}" class="nav-item nav-link">Trang chủ</a>
                            <a href="{% url 'app_store:danh_muc' 0 %}" class="nav-item nav-link">Sản phẩm</a>
                            <a href="{% url 'app_store:lien_he' %}" class="nav-item nav-link">Liên hệ</a>
                        </div>
                        <div class="navbar-nav ml-auto">
                            {% with session_khach_hang=request.session.s_khachhang %}
                                {% if session_khach_hang %}
                                    <div class="nav-item dropdown">
                                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                                            {{ session_khach_hang.first_name }} {{ session_khach_hang.last_name }}
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a href="{% url 'app_customer:thong_tin_cua_toi' %}" class="dropdown-item">Thông tin của tôi</a>
                                            <a href="{% url 'app_customer:dang_xuat' %}" class="dropdown-item">Đăng xuất</a>
                                        </div>
                                    </div>
                                {% else %}
                                    <a href="{% url 'app_customer:dang_nhap_dang_ky' %}" class="nav-item nav-link">Đăng nhập</a>
                                {% endif %}
                            {% endwith %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->      
        
        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="{% url 'app_store:trang_chu' %}">
                                <img src="{% static 'img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="search">
                            <form method = "get" action="{% url 'app_store:tim_kiem' %}">
                                <input type="text" placeholder="Nhập từ khóa cần tìm ..." name="tu_khoa" value="{{keyword}}"  autocomplete="off" required>
                                <button type = "submit" >
                                    <i class="fa fa-search">                                        
                                    </i>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="{% url 'app_cart:gio_hang' %}" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>({{ cart|length }})</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->       
        
         
        {% block main_content %}{% endblock %}
               
        
        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Liên hệ:</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh</p>
                                <p><i class="fa fa-envelope"></i>chinguyen.hcmus@gmail.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Theo dõi tại:</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Thông tin Công ty</h2>
                            <ul>
                                <li><a href="#">Về Công ty</a></li>
                                <li><a href="#">Chính sách bảo mật</a></li>
                                <li><a href="#">Điều khoản và dịch vụ</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Thông tin thanh toán</h2>
                            <ul>
                                <li><a href="#">Chính sách thanh toán</a></li>
                                <li><a href="#">Chinh sách vận chuyển</a></li>
                                <li><a href="#">Chính sách đổi trả</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>Chấp nhận thanh toán:</h2>
                            <img src="{% static 'img/payment-method.png' %}" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Được bảo hộ bởi:</h2>
                            <img src="{% static 'img/godaddy.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/norton.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/ssl.svg' %}" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">Estore</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->       
        
        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        <!-- JavaScript Libraries -->
        <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script> -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>
        
        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

app_store/templates/contact.html
{% extends '_Master.html' %}
{% block title_tab %}Liên hệ{% endblock %}
        
{% block main_content %}
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'app_store:trang_chu' %}">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Liên hệ</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Contact Start -->
        <div class="contact">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="contact-info">
                            <h2>Văn phòng</h2>
                            <h3><i class="fa fa-map-marker"></i>227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh</h3>
                            <h3><i class="fa fa-envelope"></i>chinguyen.hcmus@gmail.com</h3>
                            <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="contact-info">
                            <h2>Cửa hàng</h2>
                            <h3><i class="fa fa-map-marker"></i>227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh</h3>
                            <h3><i class="fa fa-envelope"></i>chinguyen.hcmus@gmail.com</h3>
                            <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="contact-form">
                            {{ chuoi_ket_qua|safe }}
                            <form method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" placeholder="Họ Tên" name="ho_ten"/>
                                    </div>
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" placeholder="Điện thoại" name="dien_thoai" />
                                    </div>
                                    <div class="col-md-6">
                                        <input type="email" class="form-control" placeholder="Email" name="email" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Tiêu đề" name="tieu_de"/>
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" rows="5" placeholder="Tin nhắn" name="tin_nhan"></textarea>
                                </div>
                                <div>
                                    <button class="btn" type="submit">Gửi tin nhắn</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d755.6371280854041!2d106.68329281002522!3d10.752891533068293!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ee1ff354f3f%3A0x18f40d9f2c7f8e18!2zVHJ1bmcgVMOibSBUaW4gSOG7jWMgLSDEkEggS2hvYSBI4buNYyBU4buxIE5oacOqbiAoQ1MyKQ!5e0!3m2!1svi!2s!4v1698511647197!5m2!1svi!2s" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact End -->
{% endblock %}        

app_store/templates/result.html
{% extends '_Master.html' %}
{% load static %}
{% block title_tab %}Đặt hàng thành công{% endblock %}

{% block main_content %}

    <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'app_store:trang_chu' %}">Trang chủ</a></li>
                <li class="breadcrumb-item active">Đặt hàng thành công</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Checkout Start -->
    <div class="checkout">
        <div class="container-fluid">
            <div class="text-center">
                <img src="{% static 'images/success.png' %}" width="20%" />
                <p><h2>Đặt hàng thành công</h2></p>
                <p><h4>Cảm ơn bạn đã đặt hàng. Đơn hàng của bạn sẽ được chuyển đến bạn trong thời gian sớm nhất.</h4></p>
                <br>
            </div>
        </div>
    </div>
    <!-- Checkout End -->

{% endblock %}