app_admin/urls.py
from django.urls import path
from app_admin.views import *


app_name = 'app_admin'
urlpatterns = [
    path('dang-ky-2/', dang_ky_2, name = 'dang_ky_2'),
    path('dang-nhap-2/', dang_nhap_2, name = 'dang_nhap_2'),
    path('danh-sach-nguoi-dung/', danh_sach_nguoi_dung, name = 'danh_sach_nguoi_dung'),
    path('dang-xuat-2/', dang_xuat_2, name = 'dang_xuat_2'),
]

urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from app_store.views import ProductViewSet

router = routers.DefaultRouter()
router.register('san-pham', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_store.urls')),
    path('', include('app_customer.urls')),
    path('', include('app_cart.urls')),
    path('', include('app_admin.urls')),
    path('', include('app_report.urls')),
    path('', include('app_analysis.urls')),
    path('', include('app_visualization.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_admin/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    porfolio = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to='users/', default='users/no_avatar.png')

    def __str__(self) -> str:
        return self.user.username

app_admin/forms.py
from django import forms
from django.contrib.auth.models import  User
from app_admin.models import UserProfileInfo

class FormUser(forms.ModelForm):
    username = forms.CharField(label='Username',  widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    email = forms.CharField(label='Email',  widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))
    password = forms.CharField(label='Password',  widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    confirm_password = forms.CharField(label='Confirm Password',  widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    first_name = forms.CharField(label='First name',  widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    last_name = forms.CharField(label='Last name',  widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']

class FormUserProfileInfo(forms.ModelForm):
    porfolio = forms.URLField(label ='Porfolio', widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    image = forms.ImageField(label ='Image', required=False, widget=forms.FileInput(attrs={
        'class': 'form-control-file'
    }))

    class Meta:
        model = UserProfileInfo
        exclude = ['user']

app_admin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import  User
from django.contrib.auth import authenticate, login, logout
from app_admin.models import UserProfileInfo
from app_admin.forms import FormUser, FormUserProfileInfo

# Create your views here.
def dang_ky_2(request):
    form_user = FormUser()
    form_profile = FormUserProfileInfo()
    chuoi_ket_qua = ''

    if request.POST.get('btnDangKy'):
        form_user = FormUser(data=request.POST)
        form_profile = FormUserProfileInfo(data=request.POST)
        if form_user.is_valid() and form_profile.is_valid():
            if form_user.cleaned_data['password'] == form_user.cleaned_data['confirm_password']:
                #ghi vào bảng auth user
                user = form_user.save()
                user.is_superuser = 1
                user.is_staff = 1
                user.set_password(user.password)
                user.save()

                # user profile
                profile = form_profile.save(commit=False)
                profile.user = user
                profile.porfolio = form_profile.cleaned_data['porfolio']
                if 'image' in request.FILES:
                    profile.image = request.FILES['image']
                profile.save()

                chuoi_ket_qua =  '''
                <div class="alert alert-success" role="alert">
                    Đăng ký thông tin thành công
                </div>
                '''

            else:
                chuoi_ket_qua =  '''
                <div class="alert alert-danger" role="alert">
                    Đăng ký thất bại, Vui lòng kiểm tra lại thông tin nhập
                </div>
                '''
        else:
            chuoi_ket_qua =  '''
            <div class="alert alert-danger" role="alert">
                Đăng ký thất bại, Vui lòng kiểm tra lại thông tin nhập
            </div>
            '''

    return render(request, 'dang_ky.html', {
        'form_user': form_user,
        'form_profile': form_profile,
        'chuoi_ket_qua': chuoi_ket_qua,
    })

def dang_nhap_2(request):
    if request.user.is_authenticated:
        return redirect('app_admin:danh_sach_nguoi_dung')
    
    if request.POST.get("btnDangNhap"):
        username = request.POST.get("username")
        password = request.POST.get("password")
        nguoi_dung = authenticate(request,username=username, password=password)
        profile= UserProfileInfo.objects.filter(user=nguoi_dung)
        if nguoi_dung is not None:
            login(request,nguoi_dung) #session --> user
            if profile.count() > 0:
                dict_profile = profile.values()[0]
                dict_profile['image'] = profile[0].image.url
                request.session['s_userprofile'] = dict_profile
            return redirect('app_admin:danh_sach_nguoi_dung')
    return render(request, 'dang_nhap.html')


def dang_xuat_2(request):
    logout(request) # user mặc định
    if 's_userprofile' in request.session:
        del request.session['s_userprofile']
    return redirect('app_admin:dang_nhap_2')


def danh_sach_nguoi_dung(request):
    if not request.user.is_authenticated:
        return redirect('app_admin:dang_nhap_2')

    ds_user = list(User.objects.all().values())
    ds_profile = list(UserProfileInfo.objects.all().values())
    for i in range(len(ds_user)):
        del (ds_user[i]['password'])
        ds_user[i].update(ds_profile[i])

    return render(request, 'danh_sach_nguoi_dung.html',{
        'ds_user':ds_user,
    })

app_admin/templates/_Master2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'app_admin:danh_sach_nguoi_dung' %}">Logo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'app_admin:dang_ky_2' %}">Đăng ký</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app_admin:danh_sach_nguoi_dung' %}">Danh sách người dùng</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div input class="d-flex">
                    {% if request.user.is_authenticated %}
                    <!-- Example single danger button -->
                    <div class="btn-group">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.first_name }} {{ request.user.last_name }}
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="#">Thông tin của tôi</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'app_admin:dang_xuat_2' %}">Đăng xuất</a></li>
                        </ul>
                    </div>
                    {% else  %}
                        <a href = "{% url 'app_admin:dang_nhap_2' %}"> Đăng nhập </a>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block main_content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>

app_admin/templates/dang_ky.html
{% extends "_Master2.html" %}

{% block main_content %}
<form method="post">
    {% csrf_token %} 
    <div class="mt-5">
        {{ chuoi_ket_qua|safe }}
        
        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">{{ form_user.username.label }}</label>
            <div class="col-md-10">
                {{ form_user.username }}
            </div>
        </div>
        
        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">{{ form_user.email.label }}</label>
            <div class="col-md-10">
                {{ form_user.email }}
            </div>
        </div>

        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">{{ form_user.password.label }}</label>
            <div class="col-md-10">
                {{ form_user.password }}
            </div>
        </div>

        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">{{ form_user.confirm_password.label }}</label>
            <div class="col-md-10">
                {{ form_user.confirm_password }}
            </div>
        </div>

        
        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">{{ form_user.first_name.label }}</label>
            <div class="col-md-10">
                {{ form_user.first_name }}
            </div>
        </div>

        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">{{ form_user.last_name.label }}</label>
            <div class="col-md-10">
                {{ form_user.last_name }}
            </div>
        </div>

        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">{{ form_profile.porfolio.label }}</label>
            <div class="col-md-10">
                {{ form_profile.porfolio }}
            </div>
        </div>

        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">{{ form_profile.image.label }}</label>
            <div class="col-md-10">
                {{ form_profile.image }}
            </div>
        </div>

        

        <div class="mb-3 row">
            <label class="col-md-2 col-form-label">  </label>
            <div class="col-md-10">
                <button type="submit" class="btn btn-primary"  name='btnDangKy' value="Đăng Ký"> Đăng ký </button>
                <button type="button" class="btn btn-danger"> Hủy bỏ  </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

app_admin/templates/dang_nhap.html
{% extends "_Master2.html" %}

{% block main_content %}

<form method="post">
    {% csrf_token %}
    <div class="mt-5">
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Username</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" name="username" >
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
            <input type="password" class="form-control" name="password">
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-md-2 col-form-label"></label>
            <div class="col-md-10">
                <button type="submit" class="btn btn-primary"  name='btnDangNhap' value="Đăng nhập"> Đang nhập </button>
                <button type="button" class="btn btn-danger"> Hủy bỏ  </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

app_admin/templates/danh_sach_nguoi_dung.html
{% extends "_Master2.html" %}

{% block main_content %}
<div class="mt-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">STT</th>
                <th scope="col">Username</th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Status</th>
                <th scope="col">              </th>
            </tr>
        </thead>
        <tbody>
            {% for user in ds_user %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ user.username }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>
                    {% if user.is_active %}
                        <span class="badge rounded-pill text-bg-success">Active</span>
                    {% else %}
                        <span class="badge rounded-pill text-bg-danger">Deactive</span>
                    {% endif %}
              
                </td>
                <td style="width: 20%;">
                    <button type="button" class="btn btn-secondary btn-sm">Chi tiết</button><button type="button" class="btn btn-danger btn-sm">Xóa</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}